name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Run a one-line script
        run: |
          sudo apt-get update
          sudo apt-get install -qq telegram-cli
          
      - name: Set
        run: echo '::set-output name=SELECTED_PATH::$(ls -R .)'
        id: random-path-generator
      - name: Get
        run: echo "The path is ${{ steps.random-path-generator.outputs.SELECTED_PATH }}"
      
      - name: exec
        run: |
          ./bin/telegram-cli -k server.pub
          ./bin/telegram-cli -W -e "msg smallpotato /count_activity_codes"
